GET http://localhost:5008/games

###
GET http://localhost:5008/games/1

###
POST http://localhost:5008/games
Content-Type: application/json

{
    "Name": "Super Mario Bros. Wonder",
    "GenreId": 3,
    "Price": 1,
    "ReleaseDate": "2023-10-20" 
}

###
PUT http://localhost:5008/games/1
Content-Type: application/json

{
  "name": "Street Fighter I",
  "genreId": 2,
  "price": 19.99,
  "releaseDate": "1990-07-15"
}

###
DELETE http://localhost:5008/games/1


###
GET http://localhost:5008/genres/